# Generated by Django 3.0.6 on 2020-05-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('publisher', models.CharField(max_length=100)),
                ('record_title', models.CharField(max_length=200)),
                ('read_at', models.DateTimeField()),
                ('category', models.CharField(choices=[('국내 도서', '국내 도서'), ('국외 도서', '국외 도서'), ('eBook', 'eBook')], max_length=100)),
                ('record_body', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
    ]
