# Generated by Django 3.0.6 on 2020-05-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='category',
            field=models.CharField(choices=[('krBook', '국내 도서'), ('otherBook', '국외 도서'), ('eBook', 'eBook')], max_length=100),
        ),
    ]
