# Generated by Django 2.2.5 on 2020-05-31 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0002_auto_20200530_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
