# Generated by Django 3.0.6 on 2020-05-31 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookbank', '0003_auto_20200531_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingrecord',
            name='category',
            field=models.CharField(choices=[('국내 도서', (('가정 살림', '건강 살림'), ('건강 취미', '건강 취미'))), ('외국 도서', (('ELT 사전', 'ELT 사전'), ('문학 소설', '문학 소설')))], max_length=100),
        ),
    ]
