# Generated by Django 3.0.6 on 2020-06-01 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0002_auto_20200601_2209'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadingRecord',
        ),
    ]
