# Generated by Django 3.0.6 on 2020-06-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_contacts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacts',
        ),
    ]
